version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    container_name: grid07-postgres
    environment:
      POSTGRES_DB: grid07db
      POSTGRES_USER: grid07user
      POSTGRES_PASSWORD: grid07pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grid07user -d grid07db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: grid07-redis
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
